language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files

script:
  - ./ci/verify.sh

before_script:
  - ./ci/before_script.sh
